# Headless service for Zookeeper (required for Kafka to resolve individual pods)
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  clusterIP: None # Headless service for StatefulSet DNS
  selector:
    app: zookeeper
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: peer
    - port: 3888
      name: election
---
# StatefulSet for Zookeeper
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper # Matches headless service name
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8.2
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: election
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_SERVERS
              value: |
                zookeeper-0.zookeeper:2888:3888
                zookeeper-1.zookeeper:2888:3888
                zookeeper-2.zookeeper:2888:3888
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
